- name: Wait for instances to be ready
  vars:
  uri:
    url: "http://{{ ansible_host }}:{{ hostvars[inventory_hostname].config.http_port }}/admin/api"
    method: POST
    body_format: json
    status_code: 200
    return_content: yes
    timeout: 5
    body: "{{ lookup('template', 'templates/instance_state.json.j2') }}"
  retries: "{{ retries }}"
  delay: "{{ delay }}"
  register: result
  until: >
    result is defined and
    result.json is defined and
    'data' in result.json and
    'cluster' in result.json['data'] and
    'self' in result.json['data']['cluster'] and
    'state' in result.json['data']['cluster']['self'] and
    result.json['data']['cluster']['self']['state'] in waiting_for_state
  when: stateboard is undefined or stateboard == false

- name: Wait for stateboard instance to be ready
  shell:
    cmd: supervisorctl status "{{ cartridge_app_name }}:{{ inventory_hostname }}"
  register: output
  failed_when: '"RUNNING" not in output.stdout'
  when: stateboard is defined and stateboard == true
