---
- name: Install RPM
  include_tasks: install_rpm.yml
  when: ansible_os_family == 'RedHat' and cartridge_package_path is regex('\.rpm$')
  args:
    apply:
      tags: cartridge-instances
  tags: cartridge-instances

- name: Install DEB
  include_tasks: install_deb.yml
  when: ansible_os_family == 'Debian' and cartridge_package_path is regex('\.deb$')
  args:
    apply:
      tags: cartridge-instances
  tags: cartridge-instances

- name: Install tarball
  block:
    - name: Install tarball under systemd
      include_tasks: install_targz.yml
      args:
        apply:
          tags: cartridge-instances
      when: >-
        cartridge_package_path is regex('\.tar\.gz$') and
        'supervisor' not in ansible_run_tags
    - name: Install tarball under supervisord
      include_tasks: install_targz.yml
      args:
        apply:
          tags:
            - cartridge-instances
            - supervisor
      when: >-
        cartridge_package_path is regex('\.tar\.gz$') and
        'supervisor' in ansible_run_tags
  tags: cartridge-instances, supervisor
