- name: Wait for instance to be started
  cartridge_check_instance_started:
    control_sock: '{{ instance_control_sock }}'
    stateboard: '{{ stateboard }}'
    waiting_for_state: '{{ states }}'
  register: check_instance
  until: not check_instance.failed
  retries: '{{ retries }}'
  delay: '{{ delay }}'
  any_errors_fatal: true
  when: not expelled and (stateboard is not defined or stateboard == false)

- name: Wait for stateboard instance to be ready
  shell:
    cmd: supervisorctl status "{{ cartridge_app_name }}:{{ inventory_hostname }}"
  register: output
  failed_when: '"RUNNING" not in output.stdout'
  any_errors_fatal: true
  when: stateboard is defined and stateboard == true

- name: Set instance state
  set_fact:
    instance_is_started: "{{ not check_instance.failed }}"
  when: not expelled and (stateboard is not defined or stateboard == false)
