---
- name: Manage instance parameters in runtime
  cartridge_instance:
    control_sock: '{{ instance_control_sock }}'
    config: '{{ config }}'
    cartridge_defaults: '{{ cartridge_defaults }}'
  when: >-
    not restarted and not expelled
  tags:
    - cartridge-replicasets
    - supervisor

- name: Check if instance restart is forced or required to apply changes
  block: Check instance restart (systemd)
    - name:
      cartridge_needs_restart:
        restarted: '{{ restarted }}'
        control_sock: '{{ instance_control_sock }}'
        appname: '{{ cartridge_app_name }}'
        instance_conf_file: '{{ instance_conf_file }}'
        conf_section_name: '{{ instance_conf_section }}'
        cluster_cookie: '{{ cartridge_cluster_cookie }}'
        cartridge_defaults: '{{ cartridge_defaults }}'
        config: '{{ config }}'
        stateboard: '{{ stateboard }}'
        app_conf_file: '{{ app_conf_file }}'
        bin_dir: '{{ bin_dir }}'
      notify:
        - restart-instance
      when: "'supervisor' not in ansible_run_tags"

    - name: Check instance restart (supervisord)
      cartridge_needs_restart:
        restarted: '{{ restarted }}'
        control_sock: '{{ instance_control_sock }}'
        appname: '{{ cartridge_app_name }}'
        instance_conf_file: '{{ instance_conf_file }}'
        conf_section_name: '{{ instance_conf_section }}'
        cluster_cookie: '{{ cartridge_cluster_cookie }}'
        cartridge_defaults: '{{ cartridge_defaults }}'
        config: '{{ config }}'
        stateboard: '{{ stateboard }}'
        app_conf_file: '{{ app_conf_file }}'
        bin_dir: '{{ bin_dir }}'
      notify:
        - restart-supervisor-instance
      when: "'supervisor' in ansible_run_tags"
  tags:
    - cartridge-replicasets
    - supervisor

- name: Place default config
  copy:
    content: >-
      {{
        { cartridge_app_name: cartridge_defaults | combine({"cluster_cookie": cartridge_cluster_cookie}) }
        | to_nice_yaml
      }}
    dest: '{{ app_conf_file }}'
    owner: '{{ instance_user }}'
    group: '{{ instance_group }}'
    mode: '644'
  when: not stateboard
  tags:
    - cartridge-replicasets
    - supervisor

- name: Place instance config
  copy:
    content: >-
      {{
        { instance_conf_section: config }
          | to_nice_yaml
      }}
    dest: '{{ instance_conf_file }}'
    owner: '{{ instance_user }}'
    group: '{{ instance_group }}'
    mode: '644'
  tags:
    - cartridge-replicasets
    - supervisor
