---
# - name: Reload systemd daemon
#   systemd:
#     daemon_reload: true
#   listen: reload-systemd-daemon
#   tags: cartridge-instances
#
# - name: Restart instance systemd service
#   systemd:
#     name: '{{ instance_systemd_service }}'
#     state: restarted
#     enabled: true
#   listen: restart-instance
#   tags: cartridge-instances

# - name: Restart supervisor instances
#   supervisorctl:
#     name: "{{ cartridge_app_name }}:"
#     state: present
#   listen:
#     - restart-instance
#     - reload-supervisor-daemon
#   tags: cartridge-instances
#   when: >-
#     inventory_hostname in hostvars | get_one_not_expelled_instance_for_machine(play_hosts)

- name: Ensure process group "{{ cartridge_app_name }}":* updated
  shell:
    cmd: supervisorctl update "{{ cartridge_app_name }}"
  listen:
    - reload-supervisor-daemon
  tags: cartridge-instances
  when: >-
    inventory_hostname in hostvars | get_one_not_expelled_instance_for_machine(play_hosts)


- name: Restart supervisor instances
  supervisorctl:
    name: "{{ cartridge_app_name }}:{{ inventory_hostname }}"
    state: restarted
  listen:
    - restart-instance
    - reload-supervisor-daemon
  tags: cartridge-instances
  when: >-
    inventory_hostname in hostvars | get_one_not_expelled_instance_for_machine(play_hosts)
