---
- name: Reload systemd daemon
  systemd:
    daemon_reload: true
  listen: reload-systemd-daemon

- name: Restart instance systemd service
  systemd:
    name: '{{ instance_systemd_service }}'
    state: restarted
    enabled: true
  listen: restart-instance

- name: Ensure process group is updated
  shell:
    cmd: supervisorctl update
  listen:
    - reload-supervisor-daemon
  tags:
    - never
    - supervisor
  when: >-
    'supervisor' in ansible_run_tags and
    inventory_hostname in hostvars | get_one_not_expelled_instance_for_machine(play_hosts)

- name: Restart supervisor instances
  supervisorctl:
    name: "{{ cartridge_app_name }}:{{ inventory_hostname }}"
    state: restarted
  listen:
    - restart-supervisor-instance
  when: "'supervisor' in ansible_run_tags"
